version: '3.0'

services:
  rasa:
    image: rasa/rasa:latest-full
    command: run --enable-api
    volumes:
      - ./rasa-app-data/:/app/
    environment:
      - SQLALCHEMY_SILENCE_UBER_WARNING=1
    ports:
      - "5005:5005"
    networks:
      - khas
    restart: always

  action_server:
    image: rasa/rasa-sdk:latest
    networks:
      - khas
    ports:
    - "5055:5055"
    volumes:
    - ./rasa-app-data/endpoints.yml:/app/endpoints.yml
    - "/home/rasa/rasa/rasa-app-data/actions:/app/actions"

networks:
  khas:
    external: true
